/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package automundo;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import automundo.Cliente;
import automundo.Inicio;
import automundo.dbAutomundo;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Lenovo T440
 */
public class Altascliente extends javax.swing.JFrame {

DefaultTableModel modelo = new DefaultTableModel();
        TableRowSorter trs;
        
DefaultTableModel vehiculos = new DefaultTableModel();
        TableRowSorter trs2;

    public Altascliente() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtIdCliente = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtTelefonoCliente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtClientes = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtVehiculos = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtAño = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Alta.png"))); // NOI18N
        jMenuItem1.setText("Altas");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("NOMBRE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        txtNombreCliente.setEnabled(false);
        txtNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreClienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 230, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/datos del cliente.png"))); // NOI18N
        jLabel5.setText(" ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 11, -1, -1));

        jButton1.setText("REGRESAR");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 530, 102, 49));

        btnGuardar.setText("GUARDAR");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 350, 102, 78));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("TELEFONO");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, -1));

        txtIdCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdClienteActionPerformed(evt);
            }
        });
        txtIdCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdClienteKeyTyped(evt);
            }
        });
        getContentPane().add(txtIdCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 85, -1));

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, -1, -1));

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Alta.png"))); // NOI18N
        btnNuevo.setText("Nuevo Cliente");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, -1, -1));

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/editar.png"))); // NOI18N
        btnModificar.setText("Editar Cliente");
        btnModificar.setEnabled(false);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, 153, -1));

        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/bajas.png"))); // NOI18N
        btnBorrar.setText("Borrar Cliente");
        btnBorrar.setEnabled(false);
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, 153, -1));

        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.setEnabled(false);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 460, 102, 33));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("RESUMEN DE HISTORIAL DE NOTAS DE REMISION");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("MODELO");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, -1));

        txtTelefonoCliente.setEnabled(false);
        getContentPane().add(txtTelefonoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 230, -1));

        jtClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Folio", " Telefono", "Descripcion", "Modelo Vehículo", "Total"
            }
        ));
        jScrollPane1.setViewportView(jtClientes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, 450, 90));

        jtVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Telefono", "Marca", "Modelo", "Año", "Color"
            }
        ));
        jScrollPane2.setViewportView(jtVehiculos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, -1, 90));

        jButton2.setText("NUEVO VEHÍCULO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, -1, 40));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("DATOS DEL CLIENTE");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("TELEFONO");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        txtModelo.setEnabled(false);
        getContentPane().add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 230, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("MARCA");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));

        txtMarca.setEnabled(false);
        getContentPane().add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 230, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("COLOR");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, -1));

        txtColor.setEnabled(false);
        getContentPane().add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 230, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("AÑO");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, -1));

        txtAño.setEnabled(false);
        getContentPane().add(txtAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 230, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("VEHICULOS");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, -1, 30));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("DATOS DEL VEHÍCULO");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
     
    //METODO PARA LIMPIAR 
    private void limpiar(){
        
    this.txtIdCliente.setText("");
    this.txtNombreCliente.setText("");
    this.txtTelefonoCliente.setText("");
    this.txtMarca.setText("");
    this.txtModelo.setText("");
    this.txtAño.setText("");
    this.txtColor.setText("");
    
   // this.txtDomicilio.setText("");
    //this.txtCiudad.setText("");
    
    
    this.txtNombreCliente.requestFocus();    
    }
    
    
    
    //METODO PARA DESHABILITAR
    private void deshabilitar(){
     
    
    this.txtNombreCliente.setEnabled(false);
    this.txtTelefonoCliente.setEnabled(false);
    //this.txtDomicilio.setEnabled(false);
    //this.txtCiudad.setEnabled(false);

    this.btnBorrar.setEnabled(false);
    this.btnGuardar.setEnabled(false);
    this.btnModificar.setEnabled(false);
    
    }
    
    //METODO PARA HABILITAR
    private void habilitar(){
     
    this.txtIdCliente.setEnabled(true);
    this.txtNombreCliente.setEnabled(true);
    //this.txtDomicilio.setEnabled(true);
    //this.txtCiudad.setEnabled(true);
    this.txtTelefonoCliente.setEnabled(true);
    this.btnBuscar.setEnabled(true);

    this.btnBorrar.setEnabled(true);
    this.btnGuardar.setEnabled(true);
    this.btnModificar.setEnabled(true);
    this.btnLimpiar.setEnabled(true);
    
    }
    
    //METODO PARA OBTENER LA FECHA
   // public static String fechaRegistro(){
     //   Date fecha=new Date();
       // SimpleDateFormat formatoFecha=new SimpleDateFormat("YYYY-MM-dd");
    
       // return formatoFecha.format(fecha);
   // }
    
    
    
    
    
    
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        Inicio inicio= new Inicio();
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // BOTON PARA PODER REGRESAR
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreClienteActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreClienteActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // BOTON PARA PODER CONSULTAR UN CLIENTE EN LA BASE DE DATOS MEDIANTE LA ID
         cot = db.consultaCliente(this.txtIdCliente.getText( ));
        
        if (cot == null){
            
            JOptionPane.showMessageDialog(this, "No existen registros del cliente solicitado " + this.txtIdCliente.getText() );
            
        }
        
        else{
            
            
                   this.habilitar();
           this.btnGuardar.setEnabled(false);
            
            this.txtNombreCliente.setText(cot.getNombreCliente() );
            this.txtTelefonoCliente.setText(cot.getTelefonoCliente());
            //this.txtDomicilio.setText(cot.getDomicilio());
            //this.txtCiudad.setText(cot.getCiudad());
           // this.txtdfecha.setText(cot.getFechaRegistro());
            
            try {
            jtClientes.setModel(modelo);
            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion conn = new Conexion();
            java.sql.Connection con = conn.getConexion();

            String sql = "SELECT folio, telefonocliente, rdescripcion, rmodelo, rtotal FROM notaremision";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            ResultSetMetaData rsMd = (ResultSetMetaData) rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();
           
            modelo.addColumn("Folio");
            modelo.addColumn("Telefono");
            modelo.addColumn("Descripcion");
            modelo.addColumn("Modelo Vehículo");
            modelo.addColumn("Total");

            int[] anchos = {500, 500, 500, 500, 500};
            for (int i = 0; i < jtClientes.getColumnCount(); i++) {
                jtClientes.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
            }

            while (rs.next()) {
                Object[] filas = new Object[cantidadColumnas];
                for (int i = 0; i < cantidadColumnas; i++) {
                    filas[i] = rs.getObject(i + 1);
                }
                modelo.addRow(filas);
            }

        } catch (SQLException ex) {
            System.err.println(ex.toString());
        }
           
            //TABLA DE VEHICULOS
            
              try {
            jtVehiculos.setModel(vehiculos);
            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion conn = new Conexion();
            java.sql.Connection con = conn.getConexion();

            String sql = "SELECT telefonoCliente, marca, modelo, año, color FROM cliente";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            ResultSetMetaData rsMd = (ResultSetMetaData) rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();
           
            vehiculos.addColumn("Telefono");
            vehiculos.addColumn("Marca");
            vehiculos.addColumn("Modelo");
            vehiculos.addColumn("Año");
            vehiculos.addColumn("Color");

            int[] anchos = {500, 500, 500, 500, 500};
            for (int i = 0; i < jtVehiculos.getColumnCount(); i++) {
                jtVehiculos.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
            }

            while (rs.next()) {
                Object[] filas = new Object[cantidadColumnas];
                for (int i = 0; i < cantidadColumnas; i++) {
                    filas[i] = rs.getObject(i + 1);
                }
                vehiculos.addRow(filas);
            }

        } catch (SQLException ex) {
            System.err.println(ex.toString());
        }
           
           
           
           
            this.habilitar();
            
            this.btnBorrar.setEnabled(true);
            this.btnModificar.setEnabled(true);
            this.btnGuardar.setEnabled(false);
            
            
            
            
        }
        
        
        
        
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed

// ESTE BOTON SIRVE PARA LIMPIAR TODOS LOS CAMPOS DEL FORMULARIO REGISTRO CLIENTE

    this.txtIdCliente.setText("");
    this.txtNombreCliente.setText("");
    this.txtTelefonoCliente.setText("");
    this.txtMarca.setText("");
    this.txtModelo.setText("");
    this.txtAño.setText("");
    this.txtColor.setText("");
   // this.txtDomicilio.setText("");
    //this.txtCiudad.setText("");
    this.txtNombreCliente.requestFocus(); 
    
    
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // BOTON PARA GUARDAR LOS DATOS DEL CLIENTE EN LA BASE DE DATOS

                
    boolean exito = false;
    
    
    if (this.txtNombreCliente.getText().equals("")) exito = true;
    if (this.txtTelefonoCliente.getText().equals("")) exito = true;
    if (this.txtMarca.getText().equals("")) exito = false;
    if (this.txtModelo.getText().equals("")) exito = false;
    if (this.txtAño.getText().equals("")) exito = false;
    if (this.txtColor.getText().equals("")) exito = false;
    //if (this.txtDomicilio.getText().equals("")) exito = true;
   // if (this.txtCiudad.getText().equals("")) exito = true;
  //  if (this.txtModeloCarro.getText().equals("")) exito = true;
  //  if (this.txtAñoCarro.getText().equals("")) exito = true;
  //  if (this.txtColorCarro.getText().equals("")) exito = true;
    
//if (this.txtdfecha.getText().equals("")) exito = true;
    
    
    if(exito == false){
        
        
        cot.setNombreCliente(this.txtNombreCliente.getText());
        cot.setTelefonoCliente(this.txtTelefonoCliente.getText() );
        cot.setMarca(this.txtMarca.getText() );
        cot.setModeloCarro(this.txtModelo.getText() );
        cot.setAñoCarro(this.txtAño.getText() );
        cot.setColorCarro(this.txtColor.getText() );
      //  cot.setDomicilio(this.txtDomicilio.getText() );
      //  cot.setCiudad(this.txtCiudad.getText() );
      //  cot.setModeloCarro(this.txtModeloCarro.getText());
      //  cot.setAñoCarro(this.txtAñoCarro.getText());
      //  cot.setColorCarro(this.txtColorCarro.getText());
        
// cot.setFechaRegistro(this.txtdfecha.getText());
        
       
        if(db.insertar(cot) == true){
            
            JOptionPane.showMessageDialog(this, "Ha sido guardado exitosamente"
                    + "");
          
        }
        
        else{
            
            JOptionPane.showMessageDialog(this, "Error al insertar");
            }
        
        }
        
        else{
                
            JOptionPane.showMessageDialog(this,"Falto capturar informacion");
                
        }
    
    this.limpiar();
    this.deshabilitar();
    this.txtMarca.setEnabled(false);
    this.txtModelo.setEnabled(false);
    this.txtAño.setEnabled(false);
    this.txtColor.setEnabled(false);
    
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // BOTON PARA PODER MODIFICAR UN CLIENTE QUE YA EXISTE EN LA BASE DE DATOS
        
        
            if (JOptionPane.showConfirmDialog(this, "Estas seguro de actualizar los datos del cliente seleccionado?") ==JOptionPane.YES_OPTION){
            
            cot.setNombreCliente(this.txtNombreCliente.getText() );
            cot.setTelefonoCliente(this.txtTelefonoCliente.getText() );


  
            
         
            if(db.Actualizar(cot) == true){
                
                JOptionPane.showMessageDialog(this, "Exito en la actualizacion");
                
            }
            else {
                
                JOptionPane.showMessageDialog(this, "Error no se actualizo");
                    
                }
                
            }   
            
            this.limpiar();
            this.deshabilitar();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // BOTON PARA PODER ELIMINAR A UN CLIENTE DE LA BASE DE DATOS
         if (this.txtIdCliente.getText().equals(cot)){
            
            JOptionPane.showMessageDialog(this, "Falto capturar el numero de recibo");
            
        } else{
            
        if(JOptionPane.showConfirmDialog(this, "¿Deseas Borrar el Registro?") ==JOptionPane.YES_OPTION){
            
            if(db.borrar(this.txtIdCliente.getText() ) == true){
                
             JOptionPane.showMessageDialog(this, "Se elimino con exito el registro");
                
            }else JOptionPane.showMessageDialog(this, "No fue posible borrar, surgio un ERROR");
            
        }
    }
        
        this.limpiar();
        this.deshabilitar();
        
        
        
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // BOTON PARA PODER CREAR UN NUEVO CLIENTE EN LA BASE DE DATOS
        
               if (db.verificarDrive() == false){
           JOptionPane.showMessageDialog(this, "No se encuentran instalados los drive se cerrara la aplicacion");
           System.exit(0);
           
       }
       else{
           
           this.habilitar();
           this.txtIdCliente.setText("");
           this.btnBorrar.setEnabled(false);
           this.btnModificar.setEnabled(false);
           this.txtNombreCliente.setText("");
           this.txtTelefonoCliente.setText("");
           this.txtMarca.setEnabled(true);
           this.txtModelo.setEnabled(true);
           this.txtAño.setEnabled(true);
           this.txtColor.setEnabled(true);

           
          // txtdfecha.setText(fechaRegistro());
       }
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void txtIdClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdClienteActionPerformed
        // ESTE TEXFIELD NOS INDICA EL CAMPO DONDE VA EL ID DEL CLIENTE
    }//GEN-LAST:event_txtIdClienteActionPerformed

    private void txtIdClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdClienteKeyTyped
        txtIdCliente.addKeyListener(new KeyAdapter(){
            @Override
            public void keyReleased(KeyEvent ke) {

                trs.setRowFilter(RowFilter.regexFilter(txtIdCliente.getText(), 1));
                trs2.setRowFilter(RowFilter.regexFilter(txtIdCliente.getText(), 0));
            }
        
            
        });
        trs = new TableRowSorter(modelo);
        jtClientes.setRowSorter(trs);
        trs2 = new TableRowSorter(vehiculos);
        jtVehiculos.setRowSorter(trs2);
        
        
    }//GEN-LAST:event_txtIdClienteKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         AltasVehiculo altasvehiculo= new AltasVehiculo();
        altasvehiculo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Altascliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Altascliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Altascliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Altascliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
       // java.awt.EventQueue.invokeLater(() -> {});
            new Altascliente().setVisible(true);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtClientes;
    private javax.swing.JTable jtVehiculos;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtTelefonoCliente;
    // End of variables declaration//GEN-END:variables

//OBJETOS NECESARIOS PARA PODER CONECTAR LA BASE DE DATOS    
Cliente cot = new Cliente();
dbAutomundo db = new dbAutomundo();
}
